-- ============================================================
-- FIXGO - PARTNER / TECHNICIAN DATABASE SETUP
-- Phase 8A
-- ============================================================

-- 1. Partner profiles
CREATE TABLE IF NOT EXISTS public.partner_profiles (
    id uuid PRIMARY KEY
        REFERENCES public.users(id) ON DELETE CASCADE,

    bio text,

    profile_image_path text,

    experience_years integer NOT NULL DEFAULT 0
        CHECK (experience_years >= 0),

    rating numeric(3,2) NOT NULL DEFAULT 0
        CHECK (rating >= 0 AND rating <= 5),

    total_jobs integer NOT NULL DEFAULT 0
        CHECK (total_jobs >= 0),

    is_verified boolean NOT NULL DEFAULT false,

    is_online boolean NOT NULL DEFAULT false,

    is_available boolean NOT NULL DEFAULT false,

    service_radius_km numeric(6,2) NOT NULL DEFAULT 10
        CHECK (service_radius_km > 0),

    created_at timestamptz NOT NULL DEFAULT now(),

    updated_at timestamptz NOT NULL DEFAULT now()
);


-- 2. Partner skills
CREATE TABLE IF NOT EXISTS public.partner_skills (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    partner_id uuid NOT NULL
        REFERENCES public.partner_profiles(id) ON DELETE CASCADE,

    service_id bigint NOT NULL
        REFERENCES public.services(id) ON DELETE CASCADE,

    experience_years integer NOT NULL DEFAULT 0
        CHECK (experience_years >= 0),

    created_at timestamptz NOT NULL DEFAULT now(),

    UNIQUE(partner_id, service_id)
);


-- 3. Partner service areas
CREATE TABLE IF NOT EXISTS public.partner_service_areas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    partner_id uuid NOT NULL
        REFERENCES public.partner_profiles(id) ON DELETE CASCADE,

    area_name text NOT NULL,

    latitude numeric(10,7),

    longitude numeric(10,7),

    created_at timestamptz NOT NULL DEFAULT now()
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_partner_profiles_available
ON public.partner_profiles (
    is_available,
    is_online,
    is_verified
);

CREATE INDEX IF NOT EXISTS idx_partner_skills_partner_id
ON public.partner_skills(partner_id);

CREATE INDEX IF NOT EXISTS idx_partner_skills_service_id
ON public.partner_skills(service_id);

CREATE INDEX IF NOT EXISTS idx_partner_service_areas_partner_id
ON public.partner_service_areas(partner_id);


-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS partner_profiles_updated_at
ON public.partner_profiles;

CREATE TRIGGER partner_profiles_updated_at
BEFORE UPDATE ON public.partner_profiles
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();


-- ============================================================
-- VERIFY USER IS A PARTNER
-- ============================================================

CREATE OR REPLACE FUNCTION public.check_user_is_partner()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM public.users
        WHERE id = auth.uid()
          AND role = 'partner'
    ) THEN
        RAISE EXCEPTION 'Only partner users can modify partner profile';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS check_partner_role
ON public.partner_profiles;

CREATE TRIGGER check_partner_role
BEFORE INSERT OR UPDATE ON public.partner_profiles
FOR EACH ROW
EXECUTE FUNCTION public.check_user_is_partner();


-- ============================================================
-- ENABLE RLS
-- ============================================================

ALTER TABLE public.partner_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partner_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partner_service_areas ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- PARTNER PROFILES POLICIES
-- ============================================================

DROP POLICY IF EXISTS "Authenticated users can view partner profiles"
ON public.partner_profiles;

CREATE POLICY "Authenticated users can view partner profiles"
ON public.partner_profiles
FOR SELECT
TO authenticated
USING (true);


DROP POLICY IF EXISTS "Partners can insert own profile"
ON public.partner_profiles;

CREATE POLICY "Partners can insert own profile"
ON public.partner_profiles
FOR INSERT
TO authenticated
WITH CHECK (
    id = auth.uid()
    AND EXISTS (
        SELECT 1
        FROM public.users
        WHERE id = auth.uid()
          AND role = 'partner'
    )
);


DROP POLICY IF EXISTS "Partners can update own profile"
ON public.partner_profiles;

CREATE POLICY "Partners can update own profile"
ON public.partner_profiles
FOR UPDATE
TO authenticated
USING (id = auth.uid())
WITH CHECK (id = auth.uid());


DROP POLICY IF EXISTS "Partners can delete own profile"
ON public.partner_profiles;

CREATE POLICY "Partners can delete own profile"
ON public.partner_profiles
FOR DELETE
TO authenticated
USING (id = auth.uid());


-- ============================================================
-- PARTNER SKILLS POLICIES
-- ============================================================

DROP POLICY IF EXISTS "Authenticated users can view partner skills"
ON public.partner_skills;

CREATE POLICY "Authenticated users can view partner skills"
ON public.partner_skills
FOR SELECT
TO authenticated
USING (true);


DROP POLICY IF EXISTS "Partners can insert own skills"
ON public.partner_skills;

CREATE POLICY "Partners can insert own skills"
ON public.partner_skills
FOR INSERT
TO authenticated
WITH CHECK (
    partner_id = auth.uid()
);


DROP POLICY IF EXISTS "Partners can update own skills"
ON public.partner_skills;

CREATE POLICY "Partners can update own skills"
ON public.partner_skills
FOR UPDATE
TO authenticated
USING (partner_id = auth.uid())
WITH CHECK (partner_id = auth.uid());


DROP POLICY IF EXISTS "Partners can delete own skills"
ON public.partner_skills;

CREATE POLICY "Partners can delete own skills"
ON public.partner_skills
FOR DELETE
TO authenticated
USING (partner_id = auth.uid());


-- ============================================================
-- PARTNER SERVICE AREAS POLICIES
-- ============================================================

DROP POLICY IF EXISTS "Authenticated users can view partner areas"
ON public.partner_service_areas;

CREATE POLICY "Authenticated users can view partner areas"
ON public.partner_service_areas
FOR SELECT
TO authenticated
USING (true);


DROP POLICY IF EXISTS "Partners can insert own areas"
ON public.partner_service_areas;

CREATE POLICY "Partners can insert own areas"
ON public.partner_service_areas
FOR INSERT
TO authenticated
WITH CHECK (
    partner_id = auth.uid()
);


DROP POLICY IF EXISTS "Partners can update own areas"
ON public.partner_service_areas;

CREATE POLICY "Partners can update own areas"
ON public.partner_service_areas
FOR UPDATE
TO authenticated
USING (partner_id = auth.uid())
WITH CHECK (partner_id = auth.uid());


DROP POLICY IF EXISTS "Partners can delete own areas"
ON public.partner_service_areas;

CREATE POLICY "Partners can delete own areas"
ON public.partner_service_areas
FOR DELETE
TO authenticated
USING (partner_id = auth.uid());


-- ============================================================
-- DONE
-- ============================================================