import { router, type Href, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/themed-text';
import { MaxContentWidth, Spacing } from '@/constants/theme';

export default function BookingConfirmationScreen() {
  const { name = 'Rajesh Kumar', service = 'AC Repair', price = '450', arrival = '25', location = 'Customer repair address' } = useLocalSearchParams<{ name?: string; service?: string; price?: string; arrival?: string; location?: string }>();
  const bookingId = `FG-${name.slice(0, 2).toUpperCase()}-${arrival}-${price}`;
  return <View style={styles.page}><SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><Pressable accessibilityRole="button" onPress={() => router.back()} style={styles.back}><ThemedText style={styles.backText}>Back</ThemedText></Pressable><ThemedText style={styles.brand}>FixGo</ThemedText></View>
    <View style={styles.successIcon}><ThemedText style={styles.successMark}>OK</ThemedText></View><ThemedText style={styles.title}>Booking Confirmed</ThemedText><ThemedText style={styles.subtitle}>Your repair request has been matched with a demo technician.</ThemedText>
    <View style={styles.detailsCard}><ThemedText style={styles.cardTitle}>Booking details</ThemedText><Row label="Technician" value={name} /><Row label="Service" value={service} /><Row label="Estimated price" value={`\u20B9${price} estimated`} /><Row label="Estimated arrival" value={`${arrival} min`} /><Row label="Repair location" value={location} /><Row label="Booking ID" value={bookingId} /></View>
    <View style={styles.timeline}><ThemedText style={styles.cardTitle}>Repair status</ThemedText><Status label="Request Created" complete /><Status label="Technician Selected" complete /><Status label="Technician On The Way" /><Status label="Repair In Progress" /><Status label="Repair Completed" /></View>
    <Pressable accessibilityRole="button" onPress={() => router.push({ pathname: '/repair-tracking', params: { name, service, location } } as unknown as Href)} style={styles.trackButton}><ThemedText style={styles.trackText}>Track Repair</ThemedText></Pressable>
  </ScrollView></SafeAreaView></View>;
}
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><ThemedText style={styles.label}>{label}</ThemedText><ThemedText style={styles.value}>{value}</ThemedText></View>; }
function Status({ label, complete = false }: { label: string; complete?: boolean }) { return <View style={styles.status}><View style={[styles.statusDot, complete && styles.completeDot]}><ThemedText style={styles.dotText}>{complete ? 'OK' : 'O'}</ThemedText></View><ThemedText style={[styles.statusText, complete && styles.completeText]}>{label}</ThemedText></View>; }
const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#071A2B' }, safeArea: { flex: 1, width: '100%', alignSelf: 'center', maxWidth: MaxContentWidth }, content: { padding: Spacing.four, paddingBottom: 40, gap: 16 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, back: { minHeight: 44, justifyContent: 'center', paddingRight: 14 }, backText: { color: '#72B9F2', fontSize: 16, fontWeight: '800' }, brand: { color: '#FFFFFF', fontSize: 20, fontWeight: '800' }, successIcon: { alignSelf: 'center', marginTop: 18, height: 64, width: 64, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: '#1A6E74' }, successMark: { color: '#C6FFF1', fontSize: 15, fontWeight: '900' }, title: { color: '#FFFFFF', fontSize: 31, lineHeight: 40, fontWeight: '800', textAlign: 'center' }, subtitle: { color: '#B5C9DA', fontSize: 15, lineHeight: 22, fontWeight: '500', textAlign: 'center' }, detailsCard: { borderRadius: 20, backgroundColor: '#102D43', borderWidth: 1, borderColor: '#23435B', padding: Spacing.three, gap: 12 }, cardTitle: { color: '#FFFFFF', fontSize: 18, fontWeight: '800', marginBottom: 2 }, row: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' }, label: { color: '#93B4CC', fontSize: 13, fontWeight: '700', width: 116 }, value: { color: '#EAF4FC', flex: 1, fontSize: 14, lineHeight: 20, textAlign: 'right', fontWeight: '600' }, timeline: { borderRadius: 20, backgroundColor: '#0C314B', borderWidth: 1, borderColor: '#24567A', padding: Spacing.three, gap: 13 }, status: { flexDirection: 'row', alignItems: 'center', gap: 11 }, statusDot: { width: 22, height: 22, borderRadius: 11, borderWidth: 1, borderColor: '#7191A9', alignItems: 'center', justifyContent: 'center' }, completeDot: { borderColor: '#4FD0B0', backgroundColor: '#174D51' }, dotText: { color: '#AFC4D6', fontSize: 8, fontWeight: '900' }, statusText: { color: '#AFC4D6', fontSize: 14, fontWeight: '600' }, completeText: { color: '#E9FFFA' }, trackButton: { minHeight: 58, borderRadius: 17, backgroundColor: '#2188D5', alignItems: 'center', justifyContent: 'center' }, trackText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
});
