import { router, type Href, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { SymbolView } from 'expo-symbols';

import { ThemedText } from '@/components/themed-text';
import { FixGoColors, MaxContentWidth, Radius, Spacing } from '@/constants/theme';
import { confirmLocalBooking, getActiveRequest, getSelectedTechnician, technicians } from '@/data/customer-flow';

export default function BookingConfirmationScreen() {
  const { name = 'Rajesh Kumar', service = 'AC Repair', price = '450', arrival = '25', location = 'Customer repair address' } = useLocalSearchParams<{ name?: string; service?: string; price?: string; arrival?: string; location?: string }>();
  const request = getActiveRequest();
  const technician = getSelectedTechnician() ?? technicians.find((item) => item.name === name) ?? technicians[0];
  const displayService = request?.service ?? service;
  const displayLocation = request?.location ?? location;
  const displayPrice = `${technician.price ?? Number(price)}`;
  const displayArrival = `${technician.arrival ?? Number(arrival)}`;
  const initials = name.split(' ').map((part) => part[0]).join('').slice(0, 2);
  const trackRepair = () => {
    const localRequest = request ?? { id: 'direct-request', service: displayService, description: `Your ${displayService.toLowerCase()} request`, location: displayLocation, preferredTime: 'Earliest available' };
    confirmLocalBooking(localRequest, technician);
    router.push({ pathname: '/repair-tracking', params: { name: technician.name, service: displayService, price: displayPrice, arrival: displayArrival, location: displayLocation } } as unknown as Href);
  };

  return <View style={styles.page}><SafeAreaView edges={['top']} style={styles.safeArea}>
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()} style={styles.back}><SymbolView name="chevron.left" size={16} tintColor={FixGoColors.primary} /><ThemedText style={styles.backText}>Back</ThemedText></Pressable><ThemedText style={styles.headerTitle}>Confirm Booking</ThemedText><View style={styles.headerSpacer} /></View>
      <View style={styles.intro}><View style={styles.introIcon}><SymbolView name="checkmark" size={20} tintColor={FixGoColors.card} /></View><View style={styles.introCopy}><ThemedText style={styles.eyebrow}>ONE STEP AWAY</ThemedText><ThemedText style={styles.title}>Your expert is ready</ThemedText><ThemedText style={styles.subtitle}>Review the details below, then confirm your repair visit.</ThemedText></View></View>

      <SectionTitle icon="person.fill" title="Selected technician" />
      <View style={styles.technicianCard}><View style={styles.techTop}><View style={styles.avatar}><ThemedText style={styles.avatarText}>{initials}</ThemedText></View><View style={styles.techCopy}><View style={styles.nameRow}><ThemedText style={styles.name}>{technician.name}</ThemedText><View style={styles.verified}><SymbolView name="checkmark.seal.fill" size={14} tintColor={FixGoColors.success} /><ThemedText style={styles.verifiedText}>Verified</ThemedText></View></View><ThemedText style={styles.specialty}>{technician.specialization}</ThemedText></View></View><View style={styles.techMetrics}><Stat icon="star.fill" value={`${technician.rating}`} label="rating" accent /><Stat icon="briefcase.fill" value={`${technician.jobs} jobs`} label="completed" /><Stat icon="clock.fill" value={`${displayArrival} min`} label="ETA" /><Stat icon="location.fill" value={`${technician.distance} km away`} label="distance" /></View><View style={styles.chargeRow}><View><ThemedText style={styles.chargeLabel}>Expected charge</ThemedText><ThemedText style={styles.chargeHint}>Pay after the service</ThemedText></View><ThemedText style={styles.charge}>₹{displayPrice}</ThemedText></View></View>

      <SectionTitle icon="wrench.and.screwdriver.fill" title="Repair summary" />
      <View style={styles.card}><Detail icon="wrench.and.screwdriver.fill" label="Selected service" value={displayService} /><Divider /><Detail icon="text.alignleft" label="Problem description" value={request?.description ?? `Your ${displayService.toLowerCase()} request`} /><Divider /><Detail icon="clock.fill" label="Preferred time" value={request?.preferredTime ?? 'Earliest available'} /><Divider /><Detail icon="location.fill" label="Repair location" value={displayLocation} multiLine /></View>

      <SectionTitle icon="calendar" title="Booking details" />
      <View style={styles.card}><Detail icon="house.fill" label="Technician visit" value="Home service visit" /><Divider /><Detail icon="clock.fill" label="Estimated arrival" value={`Within ${displayArrival} minutes`} /><Divider /><Detail icon="indianrupeesign.circle.fill" label="Estimated service charge" value={`₹${displayPrice}`} /></View>

      <View style={styles.priceCard}><View style={styles.priceTop}><View><ThemedText style={styles.priceKicker}>ESTIMATED TOTAL</ThemedText><ThemedText style={styles.priceValue}>₹{displayPrice}</ThemedText></View><View style={styles.priceIcon}><SymbolView name="indianrupeesign" size={21} tintColor={FixGoColors.primary} /></View></View><View style={styles.note}><SymbolView name="info.circle.fill" size={15} tintColor={FixGoColors.textSecondary} /><ThemedText style={styles.noteText}>Final price may vary if additional work or parts are required.</ThemedText></View></View>
    </ScrollView>
    <SafeAreaView edges={['bottom']} style={styles.ctaWrap}><View style={styles.ctaContent}><View><ThemedText style={styles.ctaPriceLabel}>Expected charge</ThemedText><ThemedText style={styles.ctaPrice}>₹{displayPrice}</ThemedText></View><Pressable accessibilityRole="button" accessibilityLabel="Confirm booking" onPress={trackRepair} style={styles.confirmButton}><ThemedText style={styles.confirmText}>Confirm Booking</ThemedText><SymbolView name="arrow.right" size={16} tintColor={FixGoColors.card} /></Pressable></View></SafeAreaView>
  </SafeAreaView></View>;
}

function SectionTitle({ icon, title }: { icon: 'person.fill' | 'wrench.and.screwdriver.fill' | 'calendar'; title: string }) { return <View style={styles.sectionTitle}><SymbolView name={icon} size={15} tintColor={FixGoColors.primary} /><ThemedText style={styles.sectionText}>{title}</ThemedText></View>; }
function Stat({ icon, value, label, accent = false }: { icon: 'star.fill' | 'briefcase.fill' | 'clock.fill' | 'location.fill'; value: string; label: string; accent?: boolean }) { return <View style={styles.stat}><SymbolView name={icon} size={13} tintColor={accent ? '#D89617' : FixGoColors.primary} /><ThemedText style={styles.statValue}>{value}</ThemedText><ThemedText style={styles.statLabel}>{label}</ThemedText></View>; }
function Detail({ icon, label, value, multiLine = false }: { icon: 'wrench.and.screwdriver.fill' | 'text.alignleft' | 'clock.fill' | 'location.fill' | 'house.fill' | 'indianrupeesign.circle.fill'; label: string; value: string; multiLine?: boolean }) { return <View style={styles.detail}><View style={styles.detailIcon}><SymbolView name={icon} size={15} tintColor={FixGoColors.primary} /></View><View style={styles.detailCopy}><ThemedText style={styles.detailLabel}>{label}</ThemedText><ThemedText numberOfLines={multiLine ? 2 : 1} style={styles.detailValue}>{value}</ThemedText></View></View>; }
function Divider() { return <View style={styles.divider} />; }

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: FixGoColors.background }, safeArea: { flex: 1, width: '100%', alignSelf: 'center', maxWidth: MaxContentWidth }, content: { padding: Spacing.four, paddingBottom: 128, gap: 14 },
  header: { height: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 3 }, backText: { color: FixGoColors.primary, fontSize: 15, fontWeight: '800' }, headerTitle: { color: FixGoColors.text, fontSize: 16, fontWeight: '900' }, headerSpacer: { width: 43 },
  intro: { flexDirection: 'row', gap: 12, alignItems: 'center', paddingVertical: 8 }, introIcon: { width: 46, height: 46, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: FixGoColors.success }, introCopy: { flex: 1, gap: 2 }, eyebrow: { color: FixGoColors.success, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, title: { color: FixGoColors.text, fontSize: 25, lineHeight: 30, fontWeight: '900', letterSpacing: -0.7 }, subtitle: { color: FixGoColors.textSecondary, fontSize: 13, lineHeight: 18, fontWeight: '600' },
  sectionTitle: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 4 }, sectionText: { color: FixGoColors.text, fontSize: 16, fontWeight: '900' },
  technicianCard: { gap: 14, borderRadius: Radius.large, backgroundColor: FixGoColors.card, borderWidth: 1, borderColor: FixGoColors.accent, padding: Spacing.three, shadowColor: FixGoColors.shadow, shadowOpacity: 0.08, shadowRadius: 15, shadowOffset: { width: 0, height: 5 }, elevation: 2 }, techTop: { flexDirection: 'row', alignItems: 'center', gap: 11 }, avatar: { width: 55, height: 55, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: FixGoColors.primary }, avatarText: { color: FixGoColors.card, fontSize: 16, fontWeight: '900' }, techCopy: { flex: 1, gap: 4 }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: 7, flexWrap: 'wrap' }, name: { color: FixGoColors.text, fontSize: 18, lineHeight: 23, fontWeight: '900' }, verified: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: '#ECF8F1', borderRadius: Radius.pill, paddingHorizontal: 6, paddingVertical: 3 }, verifiedText: { color: FixGoColors.success, fontSize: 9, fontWeight: '900' }, specialty: { color: FixGoColors.textSecondary, fontSize: 13, fontWeight: '700' }, techMetrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, stat: { minWidth: '22%', flexGrow: 1, gap: 2, borderRadius: Radius.small, padding: 9, backgroundColor: '#F3F7F7' }, statValue: { color: FixGoColors.text, fontSize: 12, fontWeight: '900' }, statLabel: { color: FixGoColors.textSecondary, fontSize: 9, fontWeight: '700' }, chargeRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 2 }, chargeLabel: { color: FixGoColors.textSecondary, fontSize: 12, fontWeight: '800' }, chargeHint: { color: FixGoColors.textSecondary, fontSize: 10, marginTop: 2 }, charge: { color: FixGoColors.primary, fontSize: 24, lineHeight: 28, fontWeight: '900' },
  card: { borderRadius: Radius.large, backgroundColor: FixGoColors.card, borderWidth: 1, borderColor: FixGoColors.border, paddingHorizontal: Spacing.three, shadowColor: FixGoColors.shadow, shadowOpacity: 0.04, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 1 }, detail: { minHeight: 61, flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10 }, detailIcon: { height: 34, width: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: FixGoColors.accentSurface }, detailCopy: { flex: 1, gap: 2 }, detailLabel: { color: FixGoColors.textSecondary, fontSize: 11, fontWeight: '700' }, detailValue: { color: FixGoColors.text, fontSize: 14, lineHeight: 20, fontWeight: '800' }, divider: { height: StyleSheet.hairlineWidth, backgroundColor: FixGoColors.border },
  priceCard: { borderRadius: Radius.large, gap: 13, padding: Spacing.three, backgroundColor: FixGoColors.accentSurface, borderWidth: 1, borderColor: '#BCEBED' }, priceTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, priceKicker: { color: FixGoColors.primary, fontSize: 10, fontWeight: '900', letterSpacing: 0.8 }, priceValue: { color: FixGoColors.primary, fontSize: 30, lineHeight: 35, fontWeight: '900', letterSpacing: -0.8 }, priceIcon: { width: 43, height: 43, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: FixGoColors.card }, note: { flexDirection: 'row', alignItems: 'flex-start', gap: 7, borderTopWidth: StyleSheet.hairlineWidth, borderColor: '#BCEBED', paddingTop: 11 }, noteText: { flex: 1, color: FixGoColors.textSecondary, fontSize: 12, lineHeight: 17, fontWeight: '600' },
  ctaWrap: { borderTopWidth: 1, borderColor: FixGoColors.border, backgroundColor: FixGoColors.card, paddingHorizontal: Spacing.four, paddingTop: 12 }, ctaContent: { width: '100%', maxWidth: MaxContentWidth, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 12, paddingBottom: 4 }, ctaPriceLabel: { color: FixGoColors.textSecondary, fontSize: 10, fontWeight: '800' }, ctaPrice: { color: FixGoColors.text, fontSize: 19, lineHeight: 23, fontWeight: '900' }, confirmButton: { flex: 1, minHeight: 52, borderRadius: Radius.medium, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: FixGoColors.primary }, confirmText: { color: FixGoColors.card, fontSize: 14, fontWeight: '900' },
});
