import { router, type Href, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { SymbolView } from 'expo-symbols';

import { ThemedText } from '@/components/themed-text';
import { FixGoColors, MaxContentWidth, Radius, Spacing } from '@/constants/theme';

type SortMode = 'Best Match' | 'Lowest Price' | 'Fastest Arrival' | 'Highest Rated';
const technicians = [
  { name: 'Rajesh Kumar', service: 'AC Repair', rating: 4.8, reviews: 127, years: 8, distance: 1.2, price: 450, arrival: 25, match: 94, reasons: ['Strong AC Repair expertise', 'Excellent customer rating', 'Closest available technician'] },
  { name: 'Anil Kumar', service: 'AC Repair', rating: 4.6, reviews: 89, years: 5, distance: 2.1, price: 380, arrival: 18, match: 88, reasons: ['Most competitive estimated price', 'Fastest arrival time', 'Verified AC Repair experience'] },
  { name: 'Suresh Rao', service: 'AC Repair', rating: 4.9, reviews: 164, years: 10, distance: 3.4, price: 520, arrival: 32, match: 91, reasons: ['Highest customer rating', 'Most repair experience', 'Strong service track record'] },
];

export default function TechnicianComparisonScreen() {
  const { service = 'AC Repair', location = 'Customer repair address' } = useLocalSearchParams<{ service?: string; location?: string }>();
  const [sortMode, setSortMode] = useState<SortMode>('Best Match');
  const [expanded, setExpanded] = useState<string | null>('Rajesh Kumar');
  const sortedTechnicians = useMemo(() => [...technicians].sort((a, b) => {
    if (sortMode === 'Lowest Price') return a.price - b.price;
    if (sortMode === 'Fastest Arrival') return a.arrival - b.arrival;
    if (sortMode === 'Highest Rated') return b.rating - a.rating;
    return b.match - a.match;
  }), [sortMode]);

  function chooseTechnician(technician: (typeof technicians)[number]) {
    Alert.alert('Technician selected', `${technician.name} has been selected for your repair.`, [{ text: 'Continue', onPress: () => router.push({ pathname: '/booking-confirmation', params: { name: technician.name, service, price: `${technician.price}`, arrival: `${technician.arrival}`, location } } as unknown as Href) }]);
  }

  return <View style={styles.page}><SafeAreaView edges={['top']} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()} style={styles.back}><SymbolView name="chevron.left" size={16} tintColor={FixGoColors.primary} /><ThemedText style={styles.backText}>Back</ThemedText></Pressable><ThemedText style={styles.brand}>FixGo</ThemedText><View style={styles.headerSpacer} /></View>
    <View style={styles.intro}><ThemedText style={styles.eyebrow}>YOUR REPAIR TEAM</ThemedText><ThemedText style={styles.title}>Compare technicians</ThemedText><ThemedText style={styles.subtitle}>Pick the professional that feels right for your {service.toLowerCase()} request.</ThemedText></View>
    <View style={styles.matchBanner}><View style={styles.bannerIcon}><SymbolView name="sparkles" size={22} tintColor={FixGoColors.accent} /></View><View style={styles.bannerCopy}><ThemedText style={styles.bannerKicker}>FIXGO SMART MATCH</ThemedText><ThemedText style={styles.bannerTitle}>Personalized options, sorted for your repair.</ThemedText><ThemedText style={styles.demo}>Demo comparison using mock data</ThemedText></View></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.sortRow}>{(['Best Match', 'Lowest Price', 'Fastest Arrival', 'Highest Rated'] as SortMode[]).map((option) => <Pressable key={option} accessibilityRole="button" accessibilityState={{ selected: sortMode === option }} onPress={() => setSortMode(option)} style={[styles.sortChip, sortMode === option && styles.sortChipActive]}><ThemedText style={[styles.sortText, sortMode === option && styles.sortTextActive]}>{option}</ThemedText></Pressable>)}</ScrollView>
    <View style={styles.list}>{sortedTechnicians.map((technician) => { const best = technician.match === 94; const isExpanded = expanded === technician.name; return <View key={technician.name} style={[styles.card, best && styles.bestCard]}>
      {best ? <View style={styles.bestBadge}><ThemedText style={styles.bestBadgeText}>BEST MATCH</ThemedText></View> : null}
      <View style={styles.cardTop}><View style={styles.avatar}><ThemedText style={styles.avatarText}>{technician.name.split(' ').map((part) => part[0]).join('')}</ThemedText></View><View style={styles.nameBlock}><ThemedText style={styles.name}>{technician.name}</ThemedText><View style={styles.verifiedRow}><SymbolView name="checkmark.seal.fill" size={13} tintColor={FixGoColors.success} /><ThemedText style={styles.service}>{service || technician.service}</ThemedText></View><ThemedText style={styles.mockLabel}>MOCK / DEMO TECHNICIAN</ThemedText></View><View style={styles.score}><ThemedText style={styles.scoreValue}>{technician.match}%</ThemedText><ThemedText style={styles.scoreLabel}>match</ThemedText></View></View>
      <View style={styles.metrics}><Metric value={`${technician.rating}\u2605`} label={`${technician.reviews} reviews`} /><Metric value={`${technician.years} years`} label="experience" /><Metric value={`${technician.distance} km`} label="away" /><Metric value={`\u20B9${technician.price}`} label="estimated" /><Metric value={`${technician.arrival} min`} label="arrival" /></View>
      <Pressable accessibilityRole="button" accessibilityState={{ expanded: isExpanded }} onPress={() => setExpanded(isExpanded ? null : technician.name)} style={styles.whyButton}><View style={styles.whyTitle}><SymbolView name="sparkles" size={14} tintColor={FixGoColors.primary} /><ThemedText style={styles.whyText}>Why this match?</ThemedText></View><ThemedText style={styles.whyAction}>{isExpanded ? 'Hide' : 'Show'}</ThemedText></Pressable>
      {isExpanded ? <View style={styles.reasons}>{technician.reasons.map((reason) => <View key={reason} style={styles.reasonRow}><SymbolView name="checkmark.circle.fill" size={15} tintColor={FixGoColors.success} /><ThemedText style={styles.reason}>{reason}</ThemedText></View>)}</View> : null}
      <View style={styles.actions}><Pressable accessibilityRole="button" onPress={() => Alert.alert('Demo quote', `A detailed quote for ${technician.name} will be connected next.`)} style={styles.quoteButton}><ThemedText style={styles.quoteText}>View Quote</ThemedText></Pressable><Pressable accessibilityRole="button" onPress={() => chooseTechnician(technician)} style={styles.chooseButton}><ThemedText style={styles.chooseText}>Choose Technician</ThemedText></Pressable></View>
    </View>; })}</View>
  </ScrollView></SafeAreaView></View>;
}

function Metric({ value, label }: { value: string; label: string }) { return <View style={styles.metric}><ThemedText style={styles.metricValue}>{value}</ThemedText><ThemedText style={styles.metricLabel}>{label}</ThemedText></View>; }

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: FixGoColors.background }, safeArea: { flex: 1, width: '100%', alignSelf: 'center', maxWidth: MaxContentWidth }, content: { padding: Spacing.four, paddingBottom: 44, gap: Spacing.three },
  header: { height: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 3 }, backText: { color: FixGoColors.primary, fontSize: 15, fontWeight: '800' }, brand: { color: FixGoColors.primary, fontSize: 20, fontWeight: '900', letterSpacing: -0.5 }, headerSpacer: { width: 43 },
  intro: { gap: 5, paddingTop: 7 }, eyebrow: { color: FixGoColors.success, fontSize: 10, fontWeight: '900', letterSpacing: 1.1 }, title: { color: FixGoColors.text, fontSize: 31, lineHeight: 38, fontWeight: '900', letterSpacing: -0.9 }, subtitle: { color: FixGoColors.textSecondary, fontSize: 15, lineHeight: 22, fontWeight: '600' },
  matchBanner: { borderRadius: Radius.large, padding: Spacing.three, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: FixGoColors.primary }, bannerIcon: { width: 46, height: 46, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#1E575E' }, bannerCopy: { flex: 1, gap: 3 }, bannerKicker: { color: FixGoColors.accent, fontSize: 10, fontWeight: '900', letterSpacing: 0.8 }, bannerTitle: { color: FixGoColors.card, fontSize: 15, lineHeight: 20, fontWeight: '800' }, demo: { color: '#C5DEE0', fontSize: 11, lineHeight: 16, fontWeight: '600' },
  sortRow: { gap: 8, paddingVertical: 1 }, sortChip: { minHeight: 38, justifyContent: 'center', paddingHorizontal: 13, borderRadius: Radius.pill, backgroundColor: FixGoColors.card, borderWidth: 1, borderColor: FixGoColors.border }, sortChipActive: { backgroundColor: FixGoColors.primary, borderColor: FixGoColors.primary }, sortText: { color: FixGoColors.textSecondary, fontSize: 12, fontWeight: '800' }, sortTextActive: { color: FixGoColors.card },
  list: { gap: 14 }, card: { borderRadius: Radius.large, padding: Spacing.three, gap: 13, backgroundColor: FixGoColors.card, borderWidth: 1, borderColor: FixGoColors.border, shadowColor: FixGoColors.shadow, shadowOpacity: 0.06, shadowRadius: 14, shadowOffset: { width: 0, height: 5 }, elevation: 2 }, bestCard: { borderColor: FixGoColors.accent, borderWidth: 2 }, bestBadge: { alignSelf: 'flex-start', backgroundColor: FixGoColors.accentSurface, borderRadius: Radius.pill, paddingHorizontal: 9, paddingVertical: 5, marginBottom: -3 }, bestBadgeText: { color: FixGoColors.primary, fontSize: 10, fontWeight: '900', letterSpacing: 0.7 }, cardTop: { flexDirection: 'row', alignItems: 'center', gap: 10 }, avatar: { width: 49, height: 49, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: FixGoColors.primary }, avatarText: { color: FixGoColors.card, fontSize: 14, fontWeight: '900' }, nameBlock: { flex: 1, gap: 2 }, name: { color: FixGoColors.text, fontSize: 17, lineHeight: 21, fontWeight: '900' }, verifiedRow: { flexDirection: 'row', alignItems: 'center', gap: 4 }, service: { color: FixGoColors.textSecondary, fontSize: 12, fontWeight: '700' }, mockLabel: { color: '#8A9A9C', fontSize: 8, fontWeight: '900', letterSpacing: 0.45 }, score: { minWidth: 49, alignItems: 'flex-end' }, scoreValue: { color: FixGoColors.primary, fontSize: 22, lineHeight: 24, fontWeight: '900' }, scoreLabel: { color: FixGoColors.textSecondary, fontSize: 10, fontWeight: '700' },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, metric: { minWidth: '30%', flexGrow: 1, backgroundColor: '#F3F7F7', borderRadius: Radius.small, padding: 9, gap: 2 }, metricValue: { color: FixGoColors.text, fontSize: 13, fontWeight: '900' }, metricLabel: { color: FixGoColors.textSecondary, fontSize: 10, fontWeight: '600' }, whyButton: { minHeight: 42, borderRadius: Radius.small, backgroundColor: FixGoColors.accentSurface, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12 }, whyTitle: { flexDirection: 'row', alignItems: 'center', gap: 6 }, whyText: { color: FixGoColors.primary, fontSize: 13, fontWeight: '800' }, whyAction: { color: FixGoColors.primary, fontSize: 12, fontWeight: '900' }, reasons: { gap: 7, paddingHorizontal: 2 }, reasonRow: { flexDirection: 'row', alignItems: 'center', gap: 7 }, reason: { color: FixGoColors.textSecondary, flex: 1, fontSize: 13, lineHeight: 18, fontWeight: '600' }, actions: { flexDirection: 'row', gap: 10 }, quoteButton: { flex: 1, minHeight: 47, borderRadius: Radius.small, borderWidth: 1, borderColor: FixGoColors.primary, alignItems: 'center', justifyContent: 'center' }, quoteText: { color: FixGoColors.primary, fontSize: 13, fontWeight: '900' }, chooseButton: { flex: 1.35, minHeight: 47, borderRadius: Radius.small, backgroundColor: FixGoColors.primary, alignItems: 'center', justifyContent: 'center' }, chooseText: { color: FixGoColors.card, fontSize: 13, fontWeight: '900' },
});
